### ISSUE TITLE
Option to force use of "mime" instead of "mmmagic"

### ISSUE THREAD

**Issue by bbak** [mihhail-lapushkin/grunt-css-url-embed#24]
Since "mmmagic" has some issues (e. g. doesn't detect WOFF - at least on Debian, libmagic1 5.17-1), it may be feasible to have an option to force use of "mime" - and the possibility to add additional types/file-extensions to "mime".

**Comment by mihhail-lapushkin** [comment]
Done. See https://github.com/mihhail-lapushkin/grunt-css-url-embed#usemimetypesniffing for more details.
In case you need additional MIME-type mappings, please contact the author of [mime](https://github.com/broofa/node-mime).
