### ISSUE TITLE
Embed svg urls with # in path (e.g. for filter property)

### ISSUE THREAD

**Issue by Maluen** [mihhail-lapushkin/grunt-css-url-embed#25]
Example:

>
filter: url("images/blur.svg#blur");

Right now the task looks for "images/blur.svg#blur" and can't find it, instead of searching for "images/blur.svg" and concatenating "#blur" to the base64. Example:

>
    filter: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxmaWx0ZXIgaWQ9ImJsdXIiPjxmZUdhdXNzaWFuQmx1ciBzdGREZXZpYXRpb249IjMiLz48L2ZpbHRlcj48L3N2Zz4=#blur");

blur.svg included for convenience:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
   <filter id="blur">
       <feGaussianBlur stdDeviation="3" />
   </filter>
</svg> 
```

**Comment by mihhail-lapushkin** [comment]
It seems that adding # after data URI's breaks images in WebKit.
Are you sure you want to use this feature?

**Comment by Maluen** [comment]
@mihhail-lapushkin problem is that without the data uri the missing image breaks the url anyway.

For now I've tested on Firefox and at least there works, do you see any alternatives?

**Comment by mihhail-lapushkin** [comment]
Well, you can use regular CSS filters like `filter: blur(3px)`. And you can also not embed it :)
WebKit is a big chunk of browsers, so I would suggest not using data URI's together with SVG filters.
However, if this is something you consider a must-have I can try to implement it.

**Comment by Maluen** [comment]
Unfortunately ```filter: blur(3px)``` is not supported in IE, a workaround could be to include the svg code directly into the same page of the target element and then use ```filter: url("#blur");``` the task will fail leaving the rule unchanged, that however will continue to work.

Still didn't tested this though.

**Comment by Maluen** [comment]
Reference: https://developer.mozilla.org/it/docs/Applying_SVG_effects_to_HTML_content

**Comment by mihhail-lapushkin** [comment]
You can use `/* noembed */` after `filter: url("#blur")` for task not to produce warnings or fail.
Give me a sign if you really need this feature.
Otherwise I would rather not spend my time on it.

**Comment by Maluen** [comment]
The above workaround works, thanks for your time.
