### ISSUE TITLE
Wont embed urls with trailing !important and no space

### ISSUE THREAD

**Issue by twozeroseven** [mihhail-lapushkin/grunt-css-url-embed#26]
Found a problem when running on css with trailing !important css style.
The problem arises only when there is no space between url and !important. 
Ex:  background-image: url('blahblah.gif')!important;  

Adding a space fixes the problem.

This was found in several js frameworks like ExtJS.

**Comment by mihhail-lapushkin** [comment]
Fixed in 1.6.1.
