### ISSUE TITLE
Fail on url(directory)

### ISSUE THREAD

**Issue by NielsHolt** [mihhail-lapushkin/grunt-css-url-embed#28]
If the url(..) is a directory the task fails
Some packages using  artificial contents in css-classes to pass info to JavaScript
Eg. leaflet using 
.leaflet-default-icon-path {
	background-image: url(images/);
	}
Proposal: 
Try using grunt.file.isFile instead of grunt.file.exists to test for file existing

**Comment by mihhail-lapushkin** [comment]
Fixed in 1.7.0.
