### ISSUE TITLE
TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by theNailz** [mihhail-lapushkin/grunt-css-url-embed#33]
This commit: https://github.com/mihhail-lapushkin/grunt-css-url-embed/commit/5c9a349dfbe10c64f6f3350fc2b3c5198c966a6a broke this package (version 1.11.0). Please fix the incompatibilities of the Mime module or rollback this change. 
See https://github.com/broofa/node-mime#version-2-notes

**Comment by mistakster** [comment]
Confirmed. Could you fix this issue, please?

**Comment by mihhail-lapushkin** [comment]
Ouch!
Fixed in 1.11.1. Please confirm.

**Comment by mistakster** [comment]
@mihhail-lapushkin, fixed. Thanks for the quick response. Cheers!
