### ISSUE TITLE
Custom options are not taking effect

### ISSUE THREAD

**Issue by dhanendrannewscorp** [mihhail-lapushkin/grunt-css-url-embed#34]
Hi,

When we are adding custom options in the grunt file like
`options: {
      useMimeTypeSniffing: false
    }`
which is not considered when converting image URL's into base64 embeds.

I think we need to merge the custom options into the default options in https://github.com/mihhail-lapushkin/grunt-css-url-embed/blob/master/tasks/css-url-embed.js#L208

Something like `options = { ...options, ...file.options };` in https://github.com/mihhail-lapushkin/grunt-css-url-embed/blob/master/tasks/css-url-embed.js#L211

--------------------------

Few more information:

`mmmagic` module is not giving the appropriate mime type for svg images. It is giving `image/svg+xml` for few images and `image/svg` for few images. Due to this images are broken on the site. So we added option not to use the mmmagic library, but it was not considered while converting.

**Comment by mihhail-lapushkin** [comment]
Something could might have broken with newer grunt versions...

If you have time to look into this, I would be happy to review and merge your PR.

**Comment by dhanendrannewscorp** [comment]
**UPDATE:**

Custom options is working as expected, it was an issue with my grunt setup. But `mmmagic` module issue is still there.

**Comment by dhanendrannewscorp** [comment]
So don't think it is relevant to this module. I will close this issue here as it is more with the `mmmagic`.
